Universe = vanilla
RequestCpus = 8
Request_GPUs = 0
RequestMemory = 4G
+RequestWalltime = 30000

NiceUser = true

Initialdir = /users/spraak/jponcele/JakobFHVAE/preprocessing_examples
Executable = /software/bin/matlab
Arguments = -nojvm -nodisplay -r maxNumCompThreads($(RequestCpus));

Input = augmentcgn_noisefilter.m
Log = /esat/spchtemp/scratch/jponcele/cgn_augmented/condor/condor_noisefilter.log
Output = /esat/spchtemp/scratch/jponcele/cgn_augmented/condor/condor_noisefilter.out
Error = /esat/spchtemp/scratch/jponcele/cgn_augmented/condor/condor_noisefilter.err

Queue
