Universe = vanilla

RequestCpus = 8
RequestMemory = 10G
+RequestWallTime = 36000
request_GPUs = 1

Requirements = (CUDACapability >= 3.5)\
  &&(CUDAGlobalMemoryMb >= 3000)\
  &&(machine!="spchcl23.esat.kuleuven.be")\
  &&(machine!="spchcl24.esat.kuleuven.be")\
  &&(machine!="molder.esat.kuleuven.be")\
  &&(machine!="blanche.esat.kuleuven.be")\
  &&(machine!="yperman.esat.kuleuven.be")\
  &&(machine!="bornholm.esat.kuleuven.be")\
  &&(machine!="kiviuq.esat.kuleuven.be")\
  &&(machine!="spchcl18.esat.kuleuven.be")\
  &&(machine!="spchcl19.esat.kuleuven.be")\
  &&(machine!="spchcl21.esat.kuleuven.be")\
  &&(machine!="spchcl17.esat.kuleuven.be")\
  &&(machine!="estragon.esat.kuleuven.be")

NiceUser = true
initialdir = /users/spraak/jponcele/JakobFHVAE

Executable = /esat/spchdisk/scratch/jponcele/anaconda3/envs/tf21/bin/python
Arguments = "scripts/test/run_eval.py --expdir $(expdir) --save True"

Log          = $(expdir)/condor_test.log
Output       = $(expdir)/condor_test.out
Error        = $(expdir)/condor_test.err

# usage: condor_submit jobfile.job expdir=/esat/spchdisk/scratch/jponcele/fhvae_jakob/exp config=/users/spraak/jponcele/JakobFHVAE/config.cfg

Queue
