Universe = vanilla

#cgn: 8 / 30G / 300000 / 1
#timit: 8 / 10G / 
RequestCpus = 8
RequestMemory = 10G
+RequestWallTime = 86000
request_GPUs = 1

#cgn: 5.0 / 5000
Requirements = (CUDACapability >= 3.5)\
  &&(Has_avx)\
  &&(CUDAGlobalMemoryMb >= 3000)\
  &&(machine!="goryu.esat.kuleuven.be")

NiceUser = true
initialdir = /users/spraak/jponcele/JakobFHVAE

Executable = condor/run_test_split.sh
Arguments = "$(expdir)"

Log          = $(expdir)/condor_test_split.log
Output       = $(expdir)/condor_test_split.out
Error        = $(expdir)/condor_test_split.err

# usage: condor_submit jobfile.job expdir=/esat/spchdisk/scratch/jponcele/fhvae_jakob/exp config=/users/spraak/jponcele/JakobFHVAE/config.cfg

Queue
